# .workflow/dvc.yaml
# Definisi pipeline DVC untuk proyek (Hanya tahap preprocessing saat ini)

stages:
  # Tahap Prepare:Preprocessing Data
  prepare: 
    cmd: python preprocessing/eksperimen_msml_rahayu_nur_rahmawati.py
    deps: 
      - preprocessing/eksperimen_msml_rahayu_nur_rahmawati.py
      - preprocessing/Telco-Customer-Churn.csv 
    outs:
      - preprocessing/Telco-Customer-Churn-Result.csv
    

