# .workflow/dvc.yaml
# Definisi pipeline DVC untuk proyek Anda (akan diisi nanti)

stages:
  # Tahap-tahap akan didefinisikan di sini nanti
  # Contoh:
  # preprocess_data:
  #   cmd: python preprocessing/eksperimen_msml_rahayu_nur_rahmawati.py
  #   deps:
  #     - Telco-Customer-Churn.csv
  #     - preprocessing/eksperimen_msml_rahayu_nur_rahmawati.py
  #   outs:
  #     - data/preprocessed_data.pkl
