# .github/workflows/process_data.yml

name: Preprocess Telco Churn Data

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:
  preprocess_data:
    runs-on: ubuntu-latest 

    permissions:
        contents: write
      
    steps:
    - name: Checkout repository 
      uses: actions/checkout@v4

    - name: Set up Python 
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.7'

    - name: Install dependencies 
      run: |
        python -m pip install --upgrade pip
        pip install -r preprocessing/requirements.txt 

    - name: Run data preprocessing script 
      run: |
        cd preprocessing
        python preprocessing/automate_Rahayu-Nur-R.py 

    - name: Upload preprocessed data artifact
      uses: actions/upload-artifact@v4
      with:
        name: preprocessed-telco-churn
        path: preprocessing/telco_churn_preprocessing/*
        if-no-files-found: error 
        
    - name: Commit processed data  
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add preprocessing/telco_churn_preprocessing/* git commit -m "Automated: Preprocessed data updated" || echo "No changes to commit"
        git pull origin main
        git push 
